dist: trusty
sudo: required

language: python
python:
  - "2.7"

# We must install astyle because 14.04's apt version is too old (doesn't support --dry-run)
before_install:
  - curl -L "https://sourceforge.net/projects/astyle/files/astyle/astyle%203.0/astyle_3.0_linux.tar.gz/download" | tar xvz
  - pushd astyle/build/gcc && make -j$(getconf _NPROCESSORS_ONLN) all && sudo make install && popd

# command to install dependencies
install:
  - pip install tox-travis
  - sudo apt-get install -y astyle

# command to run tests
script:
  tox


notifications:
  email:
    on_success: never