#!/bin/bash
source ~/.bash_profile
touched_files=`git diff --cached --name-only --diff-filter=ACMR`

#astyle
if [ -z $AUTO_ASTYLE_DISABLE ]; then
    ASTYLE_CONFIG="astyle.conf"
    if [ -f $ASTYLE_CONFIG ]; then
        ASTYLE=$(which astyle)
        if [ $? -ne 0 ]; then
            echo "[!] astyle not installed. Please install it via apt-get install astyle or brew install astyle" >&2
            exit 1
        fi
        C_FILES=$touched_files | egrep '\.(c|cpp|h)$'
        $C_FILES | xargs -I % sh -c '$ASTYLE --in-place --jobs=0 --max-line-length=150 % && git add % && echo astyle %'
    fi
fi

#autopep8
if [ -z $AUTOPEP8_DISABLE]; then
    autopep8=$(which autopep8)
    if [ $? -ne 0 ]; then
        echo "[!] autopep8 not installed. Please install it via pip install autopep8" >&2
        exit 1
    fi
    PY_FILES=$touched_files | egrep '\.py$'
    $PY_FILES | xargs -I % sh -c '$autopep8 --in-place --jobs=0 --max-line-length=150 % && git add % && echo autopep8 %'
fi